### ISSUE TITLE
Nothing happens when the launcher is clicked

### ISSUE THREAD

**Issue by ajalberd** [chihirobelmo/FalconBMS-Alternative-Launcher#11]
I am running BMS 4.34 and put the Hub.exe and config in /bin/x86 . This is with both a fresh install and a reinstall + run a few times. Nothing happens when the exe is clicked, or when the desktop shortcut is run. 

Are there any software requirements (.net, visual c) that I need to have installed (I have Windows 10)?

**Comment by chihirobelmo** [comment]
Did you put Hub.exe.config to Bin/x86 too?

**Comment by chihirobelmo** [comment]
Oh sorry, I was miss understanding. So you were putting both Hub.exe and Hub.exe.config to /bin/x86/ and it doesn't launch. Did you find "Error.txt" at "Falcon BMS 4.34" path? or did any error log found on windows event viewer? (https://kb.blackbaud.com/articles/Article/75433)

**Comment by ajalberd** [comment]
Yep, I fully extracted the zip with both files. 

Found this in the Application logs:

Faulting application name: Hub.exe, version: 1.3.0.0, time stamp: 0x5cc9cc9c
Faulting module name: KERNELBASE.dll, version: 10.0.17763.475, time stamp: 0x9877ee8b
Exception code: 0xe0434352
Fault offset: 0x0011c762
Faulting process id: 0x28f8
Faulting application start time: 0x01d5035394a285bf
Faulting application path: C:\Falcon BMS 4.34\Bin\x86\Hub.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 893a006e-0921-453d-95e9-43500b2cefae
Faulting package full name: 
Faulting package-relative application ID: 

I'm using Windows 10 LTSC, maybe that's the problem? I haven't had issues with any other games/programs though.

**Comment by ajalberd** [comment]
Another error:

`Application: Hub.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException

Exception Info: System.BadImageFormatException
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[], Byte[], System.Security.Policy.Evidence, System.Threading.StackCrawlMark ByRef, Boolean, Boolean, System.Security.SecurityContextSource)
   at System.Reflection.Assembly.Load(Byte[])
   at FalconBMS_Alternative_Launcher_Cs.Program.OnResolveAssembly(System.Object, System.ResolveEventArgs)
   at System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)

Exception Info: System.BadImageFormatException
   at FalconBMS_Alternative_Launcher_Cs.MainWindow+DirectInputKeyboard..ctor()
   at FalconBMS_Alternative_Launcher_Cs.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at FalconBMS_Alternative_Launcher_Cs.App.Main()
   at FalconBMS_Alternative_Launcher_Cs.Program.Main()`

**Comment by chihirobelmo** [comment]
Could you try putting these dlls to bin/x86 ?
[Dlls.zip](https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/files/3145686/Dlls.zip)

**Comment by ajalberd** [comment]
Launches just fine now, interesting!

**Comment by chihirobelmo** [comment]
I just released v1.31 fixing a critical glitch so please update the launcher, thank you.
