### ISSUE TITLE
Alternative Launcher doesn't launch Falcon BMS 4.35 anymore

### ISSUE THREAD

**Issue by Warmoer** [chihirobelmo/FalconBMS-Alternative-Launcher#35]
Alternative Launcher worked perfectly a week ago, but tonight when I wanted to launch BMS the launcher just closes and BMS does not launch. 

Windows Event Viewer summarises it as follows:
`Faulting application name: Hub.exe, version: 1.6.0.0, time stamp: 0x5fe0339c
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1316, time stamp: 0x7a6bfa05
Exception code: 0xe0434352
Fault offset: 0x001146d2
Faulting process id: 0x4e2c
Faulting application start time: 0x01d6f24e43ff5b79
Faulting application path: G:\Games\Falcon BMS 4.35\Bin\x86\Hub.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 3952c106-0d6d-4a64-8bb3-1db1ff9b5c08
Faulting package full name: 
Faulting package-relative application ID: `

Any ideas on what may be causing this? I saw at least one other person having the same issue on the Benchmark Sims Forum:
https://www.benchmarksims.org/forum/showthread.php?41176-Alternative-Launcher-doesn-t-launch-(

**Comment by Hawkeye4040** [comment]
This is a CLR exception being thrown from KernelBase.dll from the looks of it. I recommend we all start looking through that.

@Warmoer Could you please include a few more details such as what theater and any other error code type details that it tells you (if any).

I'm looking into this myself however I've been unable to replicate the issue yet.

**Comment by Hawkeye4040** [comment]
I just grabbed a full fresh copy of the latest version and it still launches BMS 4.35 fine for me here. It seems likely we'll need more information here to see exactly where the issue is and what's happening.

**Comment by Warmoer** [comment]
I am running a vanilla BMS 4.35 with no mods or theatres. There is no error message per se; clicking on the launch icon drops the app to the desktop after a second and that is it. This info is provided with the event:
`Fault bucket 1813022862042814945, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Hub.exe
P2: 1.6.0.0
P3: 5fe0339c
P4: System
P5: 4.8.4084.0
P6: 5dda3e69
P7: 2fef
P8: 29b
P9: System.ComponentModel.Win32
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA71C.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA884.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA885.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA893.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA8B3.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Hub.exe_943d73f6932838380bc4c5ab4bf7d4f5d93dc_bac662d5_ba505693-c299-4eb4-a141-562d5fe3ffed

Analysis symbol: 
Rechecking for solution: 0
Report Id: a4a7d77d-d8c3-4463-9fc2-4bf0927595d6
Report Status: 268435456
Hashed bucket: d82e07c440442e41a92926afedb959e1
Cab Guid: 0`

If there is something more helpful that I can provide, please let me know how to generate that and I will pass it on. I will look into the Kernelbase.dll issue in the meantime as well.

**Comment by Warmoer** [comment]
I uninstalled 4.35, reinstalled, added the Alt Launcher files again and copied my User files back and now it appears to be working. Not sure what broke and why, but it seems to be working for the moment. If anything happens again I will let you know - thanks for looking into this.

**Comment by Hawkeye4040** [comment]
That's actually very useful information thank you for sharing that.

**Comment by lstor** [comment]
I'm having the same issue. Stacktrace:

```
Application: Hub.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean)
   at System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding, Int32, Boolean)
   at System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding)
   at FalconBMS_Alternative_Launcher_Cs.MainWindow.executeOverride()
   at FalconBMS_Alternative_Launcher_Cs.Launcher435.execute(System.Object)
   at FalconBMS_Alternative_Launcher_Cs.MainWindow.Launch_Click(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at FalconBMS_Alternative_Launcher_Cs.App.Main()
   at FalconBMS_Alternative_Launcher_Cs.Program.Main()
```

**Comment by lstor** [comment]
Hmmm, I tried rerunning AL as admin. It still crashed, but this time I didn't get the stacktrace above. I did get this though:

```
Faulting application name: Hub.exe, version: 1.6.0.0, time stamp: 0x5fe0339c
Faulting module name: KERNELBASE.dll, version: 10.0.19041.906, time stamp: 0x26452a2a
Exception code: 0xc000041d
Fault offset: 0x0012a6e2
Faulting process id: 0x4710
Faulting application start time: 0x01d74546fe478094
Faulting application path: D:\Games\Falcon BMS 4.35\Bin\x86\Hub.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 58253079-7e5c-4fd4-988a-a51a40d6e0ad
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by lstor** [comment]
`Falcon BMS.cfg` is empty after the crash, so I'm guessing it might be related to that. Note to self: Make backups.

**Comment by lstor** [comment]
I think I know what caused it. I was running a Steam update in the background and ran out of disk space. I'm guessing the code writing the config files don't handle the no space exceptions gracefully.

**Comment by Sirtz** [comment]
Still having this issue, some help would be appreciated :)

**Comment by chihirobelmo** [comment]
Can you try this version to repro crash?
There should be an error message dump poping up

[AL162.zip](https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/files/7452960/AL162.zip)

**Comment by Hawkeye4040** [comment]
This looks like something new in Windows Security. A band-aid patch to a security issue. This change in the libs for windows has affected a lot of stuff. A lot of programs aren't able to access certain parts of the file system now. There is a different way to do it. The only problem is this is like the third time (that I can recollect) that they've changed this. So now we have to hunt down another workaround here. 

All of this is assuming I'm correct about this being the same issue of course. This looks like the same issue that is plaguing WDP right now also. Stuff that I knew for a fact that was working the last release on that, stuff I know he would have no reason to touch/change. Suddenly magically broken. All of this around the same time as said band-aid patch security update. Stlll that's technically an assumption but without any strong evidence pointing elsewhere that's where I'm going to dive in and start looking. 

But first I need to set this all up on a laptop or something off to the side with an experimental instance of BMS so as to not mess up my good logbook in the event that something gets messed up. I have to do all that all over again so this one may take me a while. This is all in my free time...

**Comment by Hawkeye4040** [comment]
> Still having this issue, some help would be appreciated :)

Strongly recommend backing up you're entire "user" directory in BMS if you haven't already.

**Comment by Sirtz** [comment]
> Can you try this version to repro crash? There should be an error message dump poping up
> 
> [AL162.zip](https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/files/7452960/AL162.zip)

We fixed it together in discord a couple days ago. The problem was that my Anne Pro 2 keyboard was causing the configuration file not to write for some reason. Unplugging the device, hiding it using "hidhide" tool or using version AL162 works. 

[Game Controllers window](https://media.discordapp.net/attachments/263470436430512142/904749938292973669/unknown.png)

**Comment by Hawkeye4040** [comment]
> > Can you try this version to repro crash? There should be an error message dump poping up
> > [AL162.zip](https://github.com/chihirobelmo/FalconBMS-Alternative-Launcher/files/7452960/AL162.zip)
> 
> We fixed it together in discord a couple days ago. The problem was that my Anne Pro 2 keyboard was causing the configuration file not to write for some reason. Unplugging the device, hiding it using "hidhide" tool or using version AL162 works.
> 
> [Game Controllers window](https://media.discordapp.net/attachments/263470436430512142/904749938292973669/unknown.png)

I am going to have to look into this keyboard specifically. That is a very interesting issue. I'll run that on my other machine I'm setting up off to the side to debug a lot of stuff with this and BMS without it affecting my personal saves or having to spend hours restoring stuff when I want to fly. I'll run it on there as soon as I can when it's all set up. That's happening in my spare time so it might take me a little bit.

**Comment by Hawkeye4040** [comment]
@chihirobelmo Have you run this one yet?
